#!/usr/bin/env bash

#  ---------------------------------------------------------------------------
#  ACK is a tool like grep, designed for programmers with large trees of heterogeneous source code
#
#  To install ack, see http://betterthangrep.com/
#  To use ack, launch terminal (mac osx) and type 'ack <some_keywords>'
#  ACK will search all files in the current directory & sub-directories
#
#  Here's how I have my config file setup. this file is located on mac osx here
#  ~/.ackrc 
#  ---------------------------------------------------------------------------

# only search with case sensitivity if there is mixed case
--smart-case

# follow symlinks
--follow

# color settings
--color-filename=white
--color-lineno=cyan
--color-match=magenta underline

# search other filetypes
--type-add
ruby=haml,rabl,builder

--type-add
css=.styl,.scss

--type-add
js=json,tmpl,jst,coffee,ts

--type-add
css=sass,scss

--type-set=md=.markdown,.md

# ignore some dirs
--ignore-dir=build
--ignore-dir=vendor/bundle
--ignore-dir=.idea
--ignore-dir=tmp
--ignore-dir=log
--ignore-dir=.tmp
--ignore-dir=coverage
--ignore-dir=dist

# ignore some files
--ignore-file=is:tags
--ignore-file=is:.tags
--ignore-file=is:.example_statuses
