#!/usr/bin/env bash

# Add tab completion for many Bash commands
if which brew &> /dev/null && [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then
	source "$(brew --prefix)/share/bash-completion/bash_completion";
elif [ -f "$(brew --prefix)/etc/bash_completion" ]; then
	source "$(brew --prefix)/etc/bash_completion;"
fi;

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend $PATH.
# * ~/.extra can be used for other settings you don’t want to commit.
# Load the shell dotfiles

filesToSource=(
  "bash_prompt"

  "exports"
  "aliases"
  "functions"
  "config"
  
  #"path"
  #"extra"
)

for file in ${filesToSource[@]}; do
  file="$HOME/.$file"
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;